
name: Deploy Ingestion ADF
run-name: Deploy Ingestion ADF

on:
  workflow_dispatch: 
  push:
    paths:
      - 'github/workflows/'

    
jobs:
  build_ARM_templates:
    name: Build ARM templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0
        
      - name: Export ARM templates
        id: export
        uses: Azure/data-factory-export-action@v1.2.0
        with:
          path: Ingestion
#           id: /subscriptions/14408b8c-b4a0-4817-8fbc-31a52b9b9399/resourceGroups/CI-CD/providers/Microsoft.DataFactory/factories/dev-mvc-adf

      - name: Upload ARM templates artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: armtemplates
          path: ${{steps.export.outputs.arm-template-directory }}
          if-no-files-found: error
          
  deploy_to_uat_ingestion_adf:
    # if: ${{ github.ref == 'refs/heads/uat' || github.ref_name == 'uat' }}
    needs: [build_ARM_templates]
    name: Deploy to TEST ADF
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: retrive SPN Certificate and private key - PEM file - from github secrets and save file
        env: 
          spn_certificate: ${{secrets.AZURE_SPN_CERTIFICATE_ACC}}
        run: |
          touch ./temp_cert_and_private_key_acc.pem
          echo "$spn_certificate" >> ./temp_cert_and_private_key_acc.pem
          
      - name: Azure Login
        uses: azure/CLI@v1
        with: 
          azcliversion: 2.36.0
          inlineScript: |
            az login --service-principal -u ${{secrets.AZURE_SPN_APP_ID_ACC}} -p temp_cert_and_private_key_acc.pem --tenant ${{secrets.AZURE_SPN_TENET}}
          enable-AzPSSession: true  
      

      - name: Download ARM templates artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: armtemplates
          path: armtemplates

      - name: Deploy to TEST
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.TEST_INGESTION_ADF_RESOURCE_GROUP_NAME}}
          dataFactoryName: ${{ secrets.TEST_INGESTION_DATA_FACTORY_NAME}}
          armTemplateFile: ./armtemplates/ARMTemplateForFactory.json
          armTemplateParametersFile: ./TEST-ARMTemplateParametersForFactory.json
          predeployment: $false

################### End of workflow file ###################
